# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b77eb7fa99693877ea88a44c6f570fde8453fbeb9443de0507a689f354949b7bb4af9a1a08890df356c1651ab0ca04a7fb9a0a3606eb035da449da9655f0fa1

test:
  secret_key_base: d8efd6c675e766a5178c114483402befa58d5d5522f2f279f8176c9a95afd0601e4c64976f6343d0d7494e437e9060b9c784c22db95c3636527dea25f8881fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
